### ISSUE TITLE
f22023104郭佳澄

### ISSUE THREAD

**Issue by gjc0610** [fit2cloud-edu/SANDA-UNIVERSITY#10]
1、姓名：郭佳澄
2、GitHub账号：gic0610
3、我收藏的项目的地址：
https://github.com/mybatis/mybatis-3
https://github.com/dotnet/maui
https://github.com/pi-hole/pi-hole
https://github.com/armbian/build

**Comment by xueqidove** [comment]
作业后续提交到指定Issue中 ：https://github.com/fit2cloud-edu/SANDA-UNIVERSITY/issues/1
