### ISSUE TITLE
1.姓名：张嘉琪

### ISSUE THREAD

**Issue by PupCoco-z** [fit2cloud-edu/SANDA-UNIVERSITY#11]
1.姓名：f23015112张嘉琪
2.分享链接：http://student.dataease2.fit2cloud.com/#/de-link/DUt4913s
3.第一个仪表板/数据大屏截图：
![屏幕截图 2024-10-15 205941](https://github.com/user-attachments/assets/44ad5685-9023-4024-9bda-3935da0b7463)
![屏幕截图 2024-10-15 205956](https://github.com/user-attachments/assets/de59f0ca-a4e3-4fa0-a988-11fc683addcc)

_Originally posted by @PupCoco-z in https://github.com/fit2cloud-edu/SANDA-UNIVERSITY/issues/9#issuecomment-2413852580_

**Comment by xueqidove** [comment]
作业后续提交到指定Issue中 ：https://github.com/fit2cloud-edu/SANDA-UNIVERSITY/issues/9
