### ISSUE TITLE
第一个仪表盘

### ISSUE THREAD

**Issue by 7Spearbattle** [fit2cloud-edu/SANDA-UNIVERSITY#13]
姓名：石岩
学号：f23015426
链接：http://student.dataease2.fit2cloud.com/#/de-link/jGiAr7ij
第一个仪表盘截图
<img width="1274" alt="第一个仪表盘" src="https://github.com/user-attachments/assets/21e59834-0f2b-4770-900b-4bb47db09ca7">

**Comment by xueqidove** [comment]
作业后续提交到指定Issue中 ：https://github.com/fit2cloud-edu/SANDA-UNIVERSITY/issues/9
