### ISSUE TITLE
b24011213张玉冰

### ISSUE THREAD

**Issue by yw9wen** [fit2cloud-edu/SANDA-UNIVERSITY#14]
1、姓名：b24011213张玉冰
2、分享链接：http://student.dataease2.fit2cloud.com/#/de-link/8dOm9G6Z
3、第一个仪表板/数据大屏截图：
![微信图片_20241015210513](https://github.com/user-attachments/assets/29c59e7d-db45-444a-b58b-62f8ac0c74a4)

**Comment by xueqidove** [comment]
作业后续提交到指定Issue中 ：https://github.com/fit2cloud-edu/SANDA-UNIVERSITY/issues/9
