### ISSUE TITLE
作业

### ISSUE THREAD

**Issue by Quan-Sixhours** [fit2cloud-edu/SANDA-UNIVERSITY#17]
1、姓名：f23078122 陆剑峰
2、分享链接：http://student.dataease2.fit2cloud.com/#/de-link/S7epHfvQ
3、第一个仪表板/数据大屏截图：

![微信图片_20241015211431](https://github.com/user-attachments/assets/9b220e05-6714-4a2f-af11-cd8b7b5116da)

**Comment by xueqidove** [comment]
作业后续提交到指定Issue中 ：https://github.com/fit2cloud-edu/SANDA-UNIVERSITY/issues/9
