### ISSUE TITLE
提交作业示例： 1、姓名：f23015401贾玉颖 2、分享链接：http://student.dataease2.fit2cloud.com/#/de-link/M44QNKFy ![Uploading 屏幕截图 2024-10-15 211104.png…]()  3、第一个仪表板/数据大屏截图：

### ISSUE THREAD

**Issue by f23015401** [fit2cloud-edu/SANDA-UNIVERSITY#18]
提交作业示例：
1、姓名：f23015401贾玉颖
2、分享链接：http://student.dataease2.fit2cloud.com/#/de-link/M44QNKFy
![Uploading 屏幕截图 2024-10-15 211104.png…]()

3、第一个仪表板/数据大屏截图：
![mmexport1728998448879](https://github.com/user-attachments/assets/a0d73747-958b-4aff-b61a-ad8dd6aa79ed)

**Comment by syl0705** [comment]
姓名：f22023110沈盈伶
分享链接：http://student.dataease2.fit2cloud.com/#/de-link/EH9Zfl0P
![微信图片_20241019213203](https://github.com/user-attachments/assets/52bd7a81-9730-4a7d-99d8-2f0bf8cda14d)

**Comment by xueqidove** [comment]
作业后续提交到指定Issue中 ：https://github.com/fit2cloud-edu/SANDA-UNIVERSITY/issues/9
