### ISSUE TITLE
作业

### ISSUE THREAD

**Issue by f23015206songbaiqing** [fit2cloud-edu/SANDA-UNIVERSITY#19]
提交作业示例：
1、姓名：f23015206宋柏青
2、分享链接：http://student.dataease2.fit2cloud.com/#/de-link/CDCh4jmS

3、第一个仪表板/数据大屏截图：
![屏幕截图 2024-10-15 211517](https://github.com/user-attachments/assets/a44fc8db-8d0b-442d-97ff-e0b60e1542bf)

**Comment by xueqidove** [comment]
作业后续提交到指定Issue中 ：https://github.com/fit2cloud-edu/SANDA-UNIVERSITY/issues/9
