### ISSUE TITLE
作业

### ISSUE THREAD

**Issue by shancaidie** [fit2cloud-edu/SANDA-UNIVERSITY#21]
1、姓名：f23015103单彩蝶
2、分享链接：http://student.dataease2.fit2cloud.com/#/de-link/0u3M66T4
![屏幕截图 2024-10-15 212235](https://github.com/user-attachments/assets/890dab19-dca8-41ad-9e1b-147d6bc97ca3)

**Comment by xueqidove** [comment]
作业后续提交到指定Issue中 ：https://github.com/fit2cloud-edu/SANDA-UNIVERSITY/issues/9
