### ISSUE TITLE
f23015212杨远帆

### ISSUE THREAD

**Issue by Dsyyf** [fit2cloud-edu/SANDA-UNIVERSITY#22]
http://student.dataease2.fit2cloud.com/#/de-link/HQvNztem
![屏幕截图 2024-10-15 211536](https://github.com/user-attachments/assets/021fe2d3-6e98-45ae-99ce-e2d1aef2886f)
![屏幕截图 2024-10-15 211647](https://github.com/user-attachments/assets/f602c9ad-0e98-425c-84e1-1621bb67b1a7)

**Comment by xueqidove** [comment]
作业后续提交到指定Issue中 ：https://github.com/fit2cloud-edu/SANDA-UNIVERSITY/issues/9
