### ISSUE TITLE
ggbond-SU

### ISSUE THREAD

**Issue by ggbond-SU** [fit2cloud-edu/SANDA-UNIVERSITY#4]
1.姓名：苏紫恒(f23011324)
2.GITHUB账号：ggbond-SU
3.我收藏的项目的地址：
  https://github.com/livekit/agents
https://github.com/lukasz-madon/awesome-remote-job

**Comment by xueqidove** [comment]
作业后续提交到指定Issue中 ：https://github.com/fit2cloud-edu/SANDA-UNIVERSITY/issues/1
