### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Yyg12** [fit2cloud-edu/SANDA-UNIVERSITY#6]
1、姓名：袁银阁
2、GitHub账号：2976701434@qq.com
3、我收藏的项目的地址：https://github.com/lucasz-madon/awesome-remote-job.git

**Comment by xueqidove** [comment]
作业后续提交到指定Issue中 ：https://github.com/fit2cloud-edu/SANDA-UNIVERSITY/issues/1
